version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    groups:
      actions:
        patterns:
          - "*"
  - package-ecosystem: npm
    directory: "/web"
    schedule:
      interval: weekly
    groups:
      web:
        patterns:
          - "*"
  - package-ecosystem: pip
    directory: "/ansible/tests"
    schedule:
      interval: weekly
    groups:
      ansible:
        patterns:
          - "*"
