// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: llamesh/v1/llamesh.proto

// The collector-to-server contract, and through the server's JSON rendering of it, the page's.

package llameshv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IngestService_Report_FullMethodName = "/llamesh.v1.IngestService/Report"
)

// IngestServiceClient is the client API for IngestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Collectors dial the server and hold one Report stream open: a Hello, then a Snapshot per server per poll.
// The server sends nothing back; the stream is bidirectional so a collector with nothing to send still
// learns, from its receive side, that the server ended the stream or refused it.
type IngestServiceClient interface {
	Report(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ReportRequest, ReportResponse], error)
}

type ingestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIngestServiceClient(cc grpc.ClientConnInterface) IngestServiceClient {
	return &ingestServiceClient{cc}
}

func (c *ingestServiceClient) Report(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ReportRequest, ReportResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &IngestService_ServiceDesc.Streams[0], IngestService_Report_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReportRequest, ReportResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IngestService_ReportClient = grpc.BidiStreamingClient[ReportRequest, ReportResponse]

// IngestServiceServer is the server API for IngestService service.
// All implementations must embed UnimplementedIngestServiceServer
// for forward compatibility.
//
// Collectors dial the server and hold one Report stream open: a Hello, then a Snapshot per server per poll.
// The server sends nothing back; the stream is bidirectional so a collector with nothing to send still
// learns, from its receive side, that the server ended the stream or refused it.
type IngestServiceServer interface {
	Report(grpc.BidiStreamingServer[ReportRequest, ReportResponse]) error
	mustEmbedUnimplementedIngestServiceServer()
}

// UnimplementedIngestServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIngestServiceServer struct{}

func (UnimplementedIngestServiceServer) Report(grpc.BidiStreamingServer[ReportRequest, ReportResponse]) error {
	return status.Error(codes.Unimplemented, "method Report not implemented")
}
func (UnimplementedIngestServiceServer) mustEmbedUnimplementedIngestServiceServer() {}
func (UnimplementedIngestServiceServer) testEmbeddedByValue()                       {}

// UnsafeIngestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IngestServiceServer will
// result in compilation errors.
type UnsafeIngestServiceServer interface {
	mustEmbedUnimplementedIngestServiceServer()
}

func RegisterIngestServiceServer(s grpc.ServiceRegistrar, srv IngestServiceServer) {
	// If the following call panics, it indicates UnimplementedIngestServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IngestService_ServiceDesc, srv)
}

func _IngestService_Report_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IngestServiceServer).Report(&grpc.GenericServerStream[ReportRequest, ReportResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IngestService_ReportServer = grpc.BidiStreamingServer[ReportRequest, ReportResponse]

// IngestService_ServiceDesc is the grpc.ServiceDesc for IngestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IngestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "llamesh.v1.IngestService",
	HandlerType: (*IngestServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Report",
			Handler:       _IngestService_Report_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "llamesh/v1/llamesh.proto",
}
