// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: llamesh/v1/llamesh.proto

// The collector-to-server contract, and through the server's JSON rendering of it, the page's.

package llameshv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Kind int32

const (
	Kind_KIND_UNSPECIFIED  Kind = 0
	Kind_KIND_LLAMA_SERVER Kind = 1 // the server, drawn as its first local device
	Kind_KIND_RPC          Kind = 2
	Kind_KIND_DEVICE       Kind = 3 // a further local device of the same server, such as a second GPU
)

// Enum value maps for Kind.
var (
	Kind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "KIND_LLAMA_SERVER",
		2: "KIND_RPC",
		3: "KIND_DEVICE",
	}
	Kind_value = map[string]int32{
		"KIND_UNSPECIFIED":  0,
		"KIND_LLAMA_SERVER": 1,
		"KIND_RPC":          2,
		"KIND_DEVICE":       3,
	}
)

func (x Kind) Enum() *Kind {
	p := new(Kind)
	*p = x
	return p
}

func (x Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_llamesh_v1_llamesh_proto_enumTypes[0].Descriptor()
}

func (Kind) Type() protoreflect.EnumType {
	return &file_llamesh_v1_llamesh_proto_enumTypes[0]
}

func (x Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Kind.Descriptor instead.
func (Kind) EnumDescriptor() ([]byte, []int) {
	return file_llamesh_v1_llamesh_proto_rawDescGZIP(), []int{0}
}

type ReportRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*ReportRequest_Hello
	//	*ReportRequest_Snapshot
	//	*ReportRequest_Gone
	Body          isReportRequest_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportRequest) Reset() {
	*x = ReportRequest{}
	mi := &file_llamesh_v1_llamesh_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportRequest) ProtoMessage() {}

func (x *ReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llamesh_v1_llamesh_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportRequest.ProtoReflect.Descriptor instead.
func (*ReportRequest) Descriptor() ([]byte, []int) {
	return file_llamesh_v1_llamesh_proto_rawDescGZIP(), []int{0}
}

func (x *ReportRequest) GetBody() isReportRequest_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ReportRequest) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Body.(*ReportRequest_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *ReportRequest) GetSnapshot() *Snapshot {
	if x != nil {
		if x, ok := x.Body.(*ReportRequest_Snapshot); ok {
			return x.Snapshot
		}
	}
	return nil
}

func (x *ReportRequest) GetGone() *Gone {
	if x != nil {
		if x, ok := x.Body.(*ReportRequest_Gone); ok {
			return x.Gone
		}
	}
	return nil
}

type isReportRequest_Body interface {
	isReportRequest_Body()
}

type ReportRequest_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type ReportRequest_Snapshot struct {
	Snapshot *Snapshot `protobuf:"bytes,2,opt,name=snapshot,proto3,oneof"`
}

type ReportRequest_Gone struct {
	Gone *Gone `protobuf:"bytes,3,opt,name=gone,proto3,oneof"`
}

func (*ReportRequest_Hello) isReportRequest_Body() {}

func (*ReportRequest_Snapshot) isReportRequest_Body() {}

func (*ReportRequest_Gone) isReportRequest_Body() {}

// A llama-server the collector was reporting has exited. The server stops replaying its picture to newly
// opened pages at once; pages already open show it stale and drop it as they do any quiet picture.
type Gone struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Gone) Reset() {
	*x = Gone{}
	mi := &file_llamesh_v1_llamesh_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Gone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gone) ProtoMessage() {}

func (x *Gone) ProtoReflect() protoreflect.Message {
	mi := &file_llamesh_v1_llamesh_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gone.ProtoReflect.Descriptor instead.
func (*Gone) Descriptor() ([]byte, []int) {
	return file_llamesh_v1_llamesh_proto_rawDescGZIP(), []int{1}
}

func (x *Gone) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type ReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResponse) Reset() {
	*x = ReportResponse{}
	mi := &file_llamesh_v1_llamesh_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResponse) ProtoMessage() {}

func (x *ReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llamesh_v1_llamesh_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResponse.ProtoReflect.Descriptor instead.
func (*ReportResponse) Descriptor() ([]byte, []int) {
	return file_llamesh_v1_llamesh_proto_rawDescGZIP(), []int{2}
}

// Who is reporting. The server names an RPC node after the collector whose addresses include the node's.
type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Addresses     []string               `protobuf:"bytes,2,rep,name=addresses,proto3" json:"addresses,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"` // the collector's build, from git describe
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_llamesh_v1_llamesh_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_llamesh_v1_llamesh_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_llamesh_v1_llamesh_proto_rawDescGZIP(), []int{3}
}

func (x *Hello) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Hello) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *Hello) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// Byte counts and rates are doubles: the page reads the server's JSON, and protobuf renders 64-bit
// integers as strings there.
type Snapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	T             float64                `protobuf:"fixed64,1,opt,name=t,proto3" json:"t,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"` // hostname of the collector's host
	Target        string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"` // the llama-server's port; with source, the page's key for this picture
	Model         *Model                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	Nodes         []*Node                `protobuf:"bytes,5,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Links         []*Link                `protobuf:"bytes,6,rep,name=links,proto3" json:"links,omitempty"`
	Totals        *Totals                `protobuf:"bytes,7,opt,name=totals,proto3" json:"totals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_llamesh_v1_llamesh_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_llamesh_v1_llamesh_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_llamesh_v1_llamesh_proto_rawDescGZIP(), []int{4}
}

func (x *Snapshot) GetT() float64 {
	if x != nil {
		return x.T
	}
	return 0
}

func (x *Snapshot) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Snapshot) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Snapshot) GetModel() *Model {
	if x != nil {
		return x.Model
	}
	return nil
}

func (x *Snapshot) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *Snapshot) GetLinks() []*Link {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *Snapshot) GetTotals() *Totals {
	if x != nil {
		return x.Totals
	}
	return nil
}

type Model struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	NCtx          int32                  `protobuf:"varint,3,opt,name=n_ctx,json=nCtx,proto3" json:"n_ctx,omitempty"`
	Build         string                 `protobuf:"bytes,4,opt,name=build,proto3" json:"build,omitempty"`
	Structure     *Structure             `protobuf:"bytes,5,opt,name=structure,proto3" json:"structure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Model) Reset() {
	*x = Model{}
	mi := &file_llamesh_v1_llamesh_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Model) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Model) ProtoMessage() {}

func (x *Model) ProtoReflect() protoreflect.Message {
	mi := &file_llamesh_v1_llamesh_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Model.ProtoReflect.Descriptor instead.
func (*Model) Descriptor() ([]byte, []int) {
	return file_llamesh_v1_llamesh_proto_rawDescGZIP(), []int{5}
}

func (x *Model) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Model) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Model) GetNCtx() int32 {
	if x != nil {
		return x.NCtx
	}
	return 0
}

func (x *Model) GetBuild() string {
	if x != nil {
		return x.Build
	}
	return ""
}

func (x *Model) GetStructure() *Structure {
	if x != nil {
		return x.Structure
	}
	return nil
}

type Structure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NLayer        int32                  `protobuf:"varint,1,opt,name=n_layer,json=nLayer,proto3" json:"n_layer,omitempty"`
	NExpert       int32                  `protobuf:"varint,2,opt,name=n_expert,json=nExpert,proto3" json:"n_expert,omitempty"`
	NExpertUsed   int32                  `protobuf:"varint,3,opt,name=n_expert_used,json=nExpertUsed,proto3" json:"n_expert_used,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Structure) Reset() {
	*x = Structure{}
	mi := &file_llamesh_v1_llamesh_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Structure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Structure) ProtoMessage() {}

func (x *Structure) ProtoReflect() protoreflect.Message {
	mi := &file_llamesh_v1_llamesh_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Structure.ProtoReflect.Descriptor instead.
func (*Structure) Descriptor() ([]byte, []int) {
	return file_llamesh_v1_llamesh_proto_rawDescGZIP(), []int{6}
}

func (x *Structure) GetNLayer() int32 {
	if x != nil {
		return x.NLayer
	}
	return 0
}

func (x *Structure) GetNExpert() int32 {
	if x != nil {
		return x.NExpert
	}
	return 0
}

func (x *Structure) GetNExpertUsed() int32 {
	if x != nil {
		return x.NExpertUsed
	}
	return 0
}

type Node struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind               Kind                   `protobuf:"varint,2,opt,name=kind,proto3,enum=llamesh.v1.Kind" json:"kind,omitempty"`
	Device             string                 `protobuf:"bytes,3,opt,name=device,proto3" json:"device,omitempty"`
	Label              string                 `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	MemTotal           float64                `protobuf:"fixed64,5,opt,name=mem_total,json=memTotal,proto3" json:"mem_total,omitempty"`
	MemModel           float64                `protobuf:"fixed64,6,opt,name=mem_model,json=memModel,proto3" json:"mem_model,omitempty"`
	MemContext         float64                `protobuf:"fixed64,7,opt,name=mem_context,json=memContext,proto3" json:"mem_context,omitempty"`
	MemCompute         float64                `protobuf:"fixed64,8,opt,name=mem_compute,json=memCompute,proto3" json:"mem_compute,omitempty"`
	Layers             *Layers                `protobuf:"bytes,9,opt,name=layers,proto3" json:"layers,omitempty"` // derived from bytes; see loadlog.LayerRanges
	TokensPerS         *float64               `protobuf:"fixed64,10,opt,name=tokens_per_s,json=tokensPerS,proto3,oneof" json:"tokens_per_s,omitempty"`
	PromptTokensPerS   *float64               `protobuf:"fixed64,11,opt,name=prompt_tokens_per_s,json=promptTokensPerS,proto3,oneof" json:"prompt_tokens_per_s,omitempty"`
	RequestsProcessing *int32                 `protobuf:"varint,12,opt,name=requests_processing,json=requestsProcessing,proto3,oneof" json:"requests_processing,omitempty"`
	Slot               *Slot                  `protobuf:"bytes,13,opt,name=slot,proto3" json:"slot,omitempty"`
	Stale              bool                   `protobuf:"varint,14,opt,name=stale,proto3" json:"stale,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_llamesh_v1_llamesh_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_llamesh_v1_llamesh_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_llamesh_v1_llamesh_proto_rawDescGZIP(), []int{7}
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Node) GetKind() Kind {
	if x != nil {
		return x.Kind
	}
	return Kind_KIND_UNSPECIFIED
}

func (x *Node) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *Node) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Node) GetMemTotal() float64 {
	if x != nil {
		return x.MemTotal
	}
	return 0
}

func (x *Node) GetMemModel() float64 {
	if x != nil {
		return x.MemModel
	}
	return 0
}

func (x *Node) GetMemContext() float64 {
	if x != nil {
		return x.MemContext
	}
	return 0
}

func (x *Node) GetMemCompute() float64 {
	if x != nil {
		return x.MemCompute
	}
	return 0
}

func (x *Node) GetLayers() *Layers {
	if x != nil {
		return x.Layers
	}
	return nil
}

func (x *Node) GetTokensPerS() float64 {
	if x != nil && x.TokensPerS != nil {
		return *x.TokensPerS
	}
	return 0
}

func (x *Node) GetPromptTokensPerS() float64 {
	if x != nil && x.PromptTokensPerS != nil {
		return *x.PromptTokensPerS
	}
	return 0
}

func (x *Node) GetRequestsProcessing() int32 {
	if x != nil && x.RequestsProcessing != nil {
		return *x.RequestsProcessing
	}
	return 0
}

func (x *Node) GetSlot() *Slot {
	if x != nil {
		return x.Slot
	}
	return nil
}

func (x *Node) GetStale() bool {
	if x != nil {
		return x.Stale
	}
	return false
}

// The contiguous range of layers a device holds, first and last inclusive, numbered from 0.
type Layers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	First         int32                  `protobuf:"varint,1,opt,name=first,proto3" json:"first,omitempty"`
	Last          int32                  `protobuf:"varint,2,opt,name=last,proto3" json:"last,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Layers) Reset() {
	*x = Layers{}
	mi := &file_llamesh_v1_llamesh_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Layers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Layers) ProtoMessage() {}

func (x *Layers) ProtoReflect() protoreflect.Message {
	mi := &file_llamesh_v1_llamesh_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Layers.ProtoReflect.Descriptor instead.
func (*Layers) Descriptor() ([]byte, []int) {
	return file_llamesh_v1_llamesh_proto_rawDescGZIP(), []int{8}
}

func (x *Layers) GetFirst() int32 {
	if x != nil {
		return x.First
	}
	return 0
}

func (x *Layers) GetLast() int32 {
	if x != nil {
		return x.Last
	}
	return 0
}

type Slot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Processing    bool                   `protobuf:"varint,1,opt,name=processing,proto3" json:"processing,omitempty"`
	NPrompt       int32                  `protobuf:"varint,2,opt,name=n_prompt,json=nPrompt,proto3" json:"n_prompt,omitempty"`
	NCached       int32                  `protobuf:"varint,3,opt,name=n_cached,json=nCached,proto3" json:"n_cached,omitempty"`
	NProcessed    int32                  `protobuf:"varint,4,opt,name=n_processed,json=nProcessed,proto3" json:"n_processed,omitempty"`
	NDecoded      int32                  `protobuf:"varint,5,opt,name=n_decoded,json=nDecoded,proto3" json:"n_decoded,omitempty"` // tokens generated so far in the request in flight
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Slot) Reset() {
	*x = Slot{}
	mi := &file_llamesh_v1_llamesh_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Slot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Slot) ProtoMessage() {}

func (x *Slot) ProtoReflect() protoreflect.Message {
	mi := &file_llamesh_v1_llamesh_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Slot.ProtoReflect.Descriptor instead.
func (*Slot) Descriptor() ([]byte, []int) {
	return file_llamesh_v1_llamesh_proto_rawDescGZIP(), []int{9}
}

func (x *Slot) GetProcessing() bool {
	if x != nil {
		return x.Processing
	}
	return false
}

func (x *Slot) GetNPrompt() int32 {
	if x != nil {
		return x.NPrompt
	}
	return 0
}

func (x *Slot) GetNCached() int32 {
	if x != nil {
		return x.NCached
	}
	return 0
}

func (x *Slot) GetNProcessed() int32 {
	if x != nil {
		return x.NProcessed
	}
	return 0
}

func (x *Slot) GetNDecoded() int32 {
	if x != nil {
		return x.NDecoded
	}
	return 0
}

type Link struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Iface         string                 `protobuf:"bytes,3,opt,name=iface,proto3" json:"iface,omitempty"`
	BytesOutPerS  float64                `protobuf:"fixed64,4,opt,name=bytes_out_per_s,json=bytesOutPerS,proto3" json:"bytes_out_per_s,omitempty"`
	BytesInPerS   float64                `protobuf:"fixed64,5,opt,name=bytes_in_per_s,json=bytesInPerS,proto3" json:"bytes_in_per_s,omitempty"`
	Stale         bool                   `protobuf:"varint,6,opt,name=stale,proto3" json:"stale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Link) Reset() {
	*x = Link{}
	mi := &file_llamesh_v1_llamesh_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Link) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Link) ProtoMessage() {}

func (x *Link) ProtoReflect() protoreflect.Message {
	mi := &file_llamesh_v1_llamesh_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Link.ProtoReflect.Descriptor instead.
func (*Link) Descriptor() ([]byte, []int) {
	return file_llamesh_v1_llamesh_proto_rawDescGZIP(), []int{10}
}

func (x *Link) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Link) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Link) GetIface() string {
	if x != nil {
		return x.Iface
	}
	return ""
}

func (x *Link) GetBytesOutPerS() float64 {
	if x != nil {
		return x.BytesOutPerS
	}
	return 0
}

func (x *Link) GetBytesInPerS() float64 {
	if x != nil {
		return x.BytesInPerS
	}
	return 0
}

func (x *Link) GetStale() bool {
	if x != nil {
		return x.Stale
	}
	return false
}

type Totals struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TokensPredicted float64                `protobuf:"fixed64,1,opt,name=tokens_predicted,json=tokensPredicted,proto3" json:"tokens_predicted,omitempty"`
	MemHeld         float64                `protobuf:"fixed64,2,opt,name=mem_held,json=memHeld,proto3" json:"mem_held,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Totals) Reset() {
	*x = Totals{}
	mi := &file_llamesh_v1_llamesh_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Totals) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Totals) ProtoMessage() {}

func (x *Totals) ProtoReflect() protoreflect.Message {
	mi := &file_llamesh_v1_llamesh_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Totals.ProtoReflect.Descriptor instead.
func (*Totals) Descriptor() ([]byte, []int) {
	return file_llamesh_v1_llamesh_proto_rawDescGZIP(), []int{11}
}

func (x *Totals) GetTokensPredicted() float64 {
	if x != nil {
		return x.TokensPredicted
	}
	return 0
}

func (x *Totals) GetMemHeld() float64 {
	if x != nil {
		return x.MemHeld
	}
	return 0
}

var File_llamesh_v1_llamesh_proto protoreflect.FileDescriptor

const file_llamesh_v1_llamesh_proto_rawDesc = "" +
	"\n" +
	"\x18llamesh/v1/llamesh.proto\x12\n" +
	"llamesh.v1\"\x9e\x01\n" +
	"\rReportRequest\x12)\n" +
	"\x05hello\x18\x01 \x01(\v2\x11.llamesh.v1.HelloH\x00R\x05hello\x122\n" +
	"\bsnapshot\x18\x02 \x01(\v2\x14.llamesh.v1.SnapshotH\x00R\bsnapshot\x12&\n" +
	"\x04gone\x18\x03 \x01(\v2\x10.llamesh.v1.GoneH\x00R\x04goneB\x06\n" +
	"\x04body\"\x1e\n" +
	"\x04Gone\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\"\x10\n" +
	"\x0eReportResponse\"S\n" +
	"\x05Hello\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x1c\n" +
	"\taddresses\x18\x02 \x03(\tR\taddresses\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"\xed\x01\n" +
	"\bSnapshot\x12\f\n" +
	"\x01t\x18\x01 \x01(\x01R\x01t\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x12'\n" +
	"\x05model\x18\x04 \x01(\v2\x11.llamesh.v1.ModelR\x05model\x12&\n" +
	"\x05nodes\x18\x05 \x03(\v2\x10.llamesh.v1.NodeR\x05nodes\x12&\n" +
	"\x05links\x18\x06 \x03(\v2\x10.llamesh.v1.LinkR\x05links\x12*\n" +
	"\x06totals\x18\a \x01(\v2\x12.llamesh.v1.TotalsR\x06totals\"\x8f\x01\n" +
	"\x05Model\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x13\n" +
	"\x05n_ctx\x18\x03 \x01(\x05R\x04nCtx\x12\x14\n" +
	"\x05build\x18\x04 \x01(\tR\x05build\x123\n" +
	"\tstructure\x18\x05 \x01(\v2\x15.llamesh.v1.StructureR\tstructure\"c\n" +
	"\tStructure\x12\x17\n" +
	"\an_layer\x18\x01 \x01(\x05R\x06nLayer\x12\x19\n" +
	"\bn_expert\x18\x02 \x01(\x05R\anExpert\x12\"\n" +
	"\rn_expert_used\x18\x03 \x01(\x05R\vnExpertUsed\"\xa0\x04\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12$\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x10.llamesh.v1.KindR\x04kind\x12\x16\n" +
	"\x06device\x18\x03 \x01(\tR\x06device\x12\x14\n" +
	"\x05label\x18\x04 \x01(\tR\x05label\x12\x1b\n" +
	"\tmem_total\x18\x05 \x01(\x01R\bmemTotal\x12\x1b\n" +
	"\tmem_model\x18\x06 \x01(\x01R\bmemModel\x12\x1f\n" +
	"\vmem_context\x18\a \x01(\x01R\n" +
	"memContext\x12\x1f\n" +
	"\vmem_compute\x18\b \x01(\x01R\n" +
	"memCompute\x12*\n" +
	"\x06layers\x18\t \x01(\v2\x12.llamesh.v1.LayersR\x06layers\x12%\n" +
	"\ftokens_per_s\x18\n" +
	" \x01(\x01H\x00R\n" +
	"tokensPerS\x88\x01\x01\x122\n" +
	"\x13prompt_tokens_per_s\x18\v \x01(\x01H\x01R\x10promptTokensPerS\x88\x01\x01\x124\n" +
	"\x13requests_processing\x18\f \x01(\x05H\x02R\x12requestsProcessing\x88\x01\x01\x12$\n" +
	"\x04slot\x18\r \x01(\v2\x10.llamesh.v1.SlotR\x04slot\x12\x14\n" +
	"\x05stale\x18\x0e \x01(\bR\x05staleB\x0f\n" +
	"\r_tokens_per_sB\x16\n" +
	"\x14_prompt_tokens_per_sB\x16\n" +
	"\x14_requests_processing\"2\n" +
	"\x06Layers\x12\x14\n" +
	"\x05first\x18\x01 \x01(\x05R\x05first\x12\x12\n" +
	"\x04last\x18\x02 \x01(\x05R\x04last\"\x9a\x01\n" +
	"\x04Slot\x12\x1e\n" +
	"\n" +
	"processing\x18\x01 \x01(\bR\n" +
	"processing\x12\x19\n" +
	"\bn_prompt\x18\x02 \x01(\x05R\anPrompt\x12\x19\n" +
	"\bn_cached\x18\x03 \x01(\x05R\anCached\x12\x1f\n" +
	"\vn_processed\x18\x04 \x01(\x05R\n" +
	"nProcessed\x12\x1b\n" +
	"\tn_decoded\x18\x05 \x01(\x05R\bnDecoded\"\xa2\x01\n" +
	"\x04Link\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x14\n" +
	"\x05iface\x18\x03 \x01(\tR\x05iface\x12%\n" +
	"\x0fbytes_out_per_s\x18\x04 \x01(\x01R\fbytesOutPerS\x12#\n" +
	"\x0ebytes_in_per_s\x18\x05 \x01(\x01R\vbytesInPerS\x12\x14\n" +
	"\x05stale\x18\x06 \x01(\bR\x05stale\"N\n" +
	"\x06Totals\x12)\n" +
	"\x10tokens_predicted\x18\x01 \x01(\x01R\x0ftokensPredicted\x12\x19\n" +
	"\bmem_held\x18\x02 \x01(\x01R\amemHeld*R\n" +
	"\x04Kind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11KIND_LLAMA_SERVER\x10\x01\x12\f\n" +
	"\bKIND_RPC\x10\x02\x12\x0f\n" +
	"\vKIND_DEVICE\x10\x032T\n" +
	"\rIngestService\x12C\n" +
	"\x06Report\x12\x19.llamesh.v1.ReportRequest\x1a\x1a.llamesh.v1.ReportResponse(\x010\x01B=Z;github.com/benemon/llamesh/internal/pb/llamesh/v1;llameshv1b\x06proto3"

var (
	file_llamesh_v1_llamesh_proto_rawDescOnce sync.Once
	file_llamesh_v1_llamesh_proto_rawDescData []byte
)

func file_llamesh_v1_llamesh_proto_rawDescGZIP() []byte {
	file_llamesh_v1_llamesh_proto_rawDescOnce.Do(func() {
		file_llamesh_v1_llamesh_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_llamesh_v1_llamesh_proto_rawDesc), len(file_llamesh_v1_llamesh_proto_rawDesc)))
	})
	return file_llamesh_v1_llamesh_proto_rawDescData
}

var file_llamesh_v1_llamesh_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_llamesh_v1_llamesh_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_llamesh_v1_llamesh_proto_goTypes = []any{
	(Kind)(0),              // 0: llamesh.v1.Kind
	(*ReportRequest)(nil),  // 1: llamesh.v1.ReportRequest
	(*Gone)(nil),           // 2: llamesh.v1.Gone
	(*ReportResponse)(nil), // 3: llamesh.v1.ReportResponse
	(*Hello)(nil),          // 4: llamesh.v1.Hello
	(*Snapshot)(nil),       // 5: llamesh.v1.Snapshot
	(*Model)(nil),          // 6: llamesh.v1.Model
	(*Structure)(nil),      // 7: llamesh.v1.Structure
	(*Node)(nil),           // 8: llamesh.v1.Node
	(*Layers)(nil),         // 9: llamesh.v1.Layers
	(*Slot)(nil),           // 10: llamesh.v1.Slot
	(*Link)(nil),           // 11: llamesh.v1.Link
	(*Totals)(nil),         // 12: llamesh.v1.Totals
}
var file_llamesh_v1_llamesh_proto_depIdxs = []int32{
	4,  // 0: llamesh.v1.ReportRequest.hello:type_name -> llamesh.v1.Hello
	5,  // 1: llamesh.v1.ReportRequest.snapshot:type_name -> llamesh.v1.Snapshot
	2,  // 2: llamesh.v1.ReportRequest.gone:type_name -> llamesh.v1.Gone
	6,  // 3: llamesh.v1.Snapshot.model:type_name -> llamesh.v1.Model
	8,  // 4: llamesh.v1.Snapshot.nodes:type_name -> llamesh.v1.Node
	11, // 5: llamesh.v1.Snapshot.links:type_name -> llamesh.v1.Link
	12, // 6: llamesh.v1.Snapshot.totals:type_name -> llamesh.v1.Totals
	7,  // 7: llamesh.v1.Model.structure:type_name -> llamesh.v1.Structure
	0,  // 8: llamesh.v1.Node.kind:type_name -> llamesh.v1.Kind
	9,  // 9: llamesh.v1.Node.layers:type_name -> llamesh.v1.Layers
	10, // 10: llamesh.v1.Node.slot:type_name -> llamesh.v1.Slot
	1,  // 11: llamesh.v1.IngestService.Report:input_type -> llamesh.v1.ReportRequest
	3,  // 12: llamesh.v1.IngestService.Report:output_type -> llamesh.v1.ReportResponse
	12, // [12:13] is the sub-list for method output_type
	11, // [11:12] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_llamesh_v1_llamesh_proto_init() }
func file_llamesh_v1_llamesh_proto_init() {
	if File_llamesh_v1_llamesh_proto != nil {
		return
	}
	file_llamesh_v1_llamesh_proto_msgTypes[0].OneofWrappers = []any{
		(*ReportRequest_Hello)(nil),
		(*ReportRequest_Snapshot)(nil),
		(*ReportRequest_Gone)(nil),
	}
	file_llamesh_v1_llamesh_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_llamesh_v1_llamesh_proto_rawDesc), len(file_llamesh_v1_llamesh_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_llamesh_v1_llamesh_proto_goTypes,
		DependencyIndexes: file_llamesh_v1_llamesh_proto_depIdxs,
		EnumInfos:         file_llamesh_v1_llamesh_proto_enumTypes,
		MessageInfos:      file_llamesh_v1_llamesh_proto_msgTypes,
	}.Build()
	File_llamesh_v1_llamesh_proto = out.File
	file_llamesh_v1_llamesh_proto_goTypes = nil
	file_llamesh_v1_llamesh_proto_depIdxs = nil
}
