// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.4
//   protoc               unknown
// source: llamesh/v1/llamesh.proto

/* eslint-disable */

export const protobufPackage = "llamesh.v1";

export enum Kind {
  KIND_UNSPECIFIED = "KIND_UNSPECIFIED",
  /** KIND_LLAMA_SERVER - the server, drawn as its first local device */
  KIND_LLAMA_SERVER = "KIND_LLAMA_SERVER",
  KIND_RPC = "KIND_RPC",
  /** KIND_DEVICE - a further local device of the same server, such as a second GPU */
  KIND_DEVICE = "KIND_DEVICE",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export interface ReportRequest {
  hello?: Hello | undefined;
  snapshot?: Snapshot | undefined;
  gone?: Gone | undefined;
}

/**
 * A model server the collector was reporting has exited. The server stops replaying its picture to newly
 * opened pages at once; pages already open show it stale and drop it as they do any quiet picture.
 */
export interface Gone {
  target: string;
}

export interface ReportResponse {
}

/** Who is reporting. The server names an RPC node after the collector whose addresses include the node's. */
export interface Hello {
  host: string;
  addresses: string[];
  /** the collector's build, from git describe */
  version: string;
}

/**
 * Byte counts and rates are doubles: the page reads the server's JSON, and protobuf renders 64-bit
 * integers as strings there.
 */
export interface Snapshot {
  t: number;
  /** hostname of the collector's host */
  source: string;
  /** the model server's port; with source, the page's key for this picture */
  target: string;
  model?: Model | undefined;
  nodes: Node[];
  links: Link[];
  totals?: Totals | undefined;
}

export interface Model {
  path: string;
  name: string;
  n_ctx: number;
  build: string;
  structure?: Structure | undefined;
  engine: string;
}

export interface Structure {
  n_layer: number;
  n_expert: number;
  n_expert_used: number;
}

export interface Node {
  id: string;
  kind: Kind;
  device: string;
  label: string;
  mem_total?: number | undefined;
  mem_model?: number | undefined;
  mem_context?: number | undefined;
  mem_compute?: number | undefined;
  layers?: Layers | undefined;
  tokens_per_s?: number | undefined;
  prompt_tokens_per_s?: number | undefined;
  requests_processing?: number | undefined;
  slot?: Slot | undefined;
  stale: boolean;
  requests_queued?: number | undefined;
}

/** The contiguous range of layers a device holds, first and last inclusive, numbered from 0. */
export interface Layers {
  first: number;
  last: number;
}

export interface Slot {
  processing: boolean;
  n_prompt: number;
  n_cached: number;
  n_processed: number;
  /** tokens generated so far in the request in flight */
  n_decoded: number;
}

export interface Link {
  from: string;
  to: string;
  iface: string;
  bytes_out_per_s: number;
  bytes_in_per_s: number;
  stale: boolean;
}

export interface Totals {
  tokens_predicted: number;
  mem_held?: number | undefined;
}
